# Netlify 배포 설정 파일
# ISO 인증정보 검색 시스템

[build]
  # 프론트엔드 + 서버리스 함수 배포
  command = "npm run build"
  # Vite 빌드 결과물
  publish = "dist"
  # Node.js 버전
  node_version = "18"

# Netlify Functions 설정
[functions]
  # Node.js 18 런타임 사용
  node_bundler = "esbuild"
  # 함수가 위치할 디렉토리
  directory = "netlify/functions"

# 함수별 타임아웃 설정
[functions.trpc]
  # 무료 플랜: 10초 제한
  timeout = 10

# API 라우팅 리다이렉션
[[redirects]]
  from = "/api/trpc/*"
  to = "/.netlify/functions/trpc/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA (Single Page Application) 리다이렉트
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 환경 변수 (로컬 개발용)
# 실제 프로덕션 환경 변수는 Netlify 대시보드에서 설정
[context.development.environment]
  NODE_ENV = "development"

[context.production.environment]
  NODE_ENV = "production"

# 헤더 설정
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET,POST,OPTIONS"
    Access-Control-Allow-Headers = "Content-Type,Authorization"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"

